---
title: "Manipulação de Dados"
author: "Hugo Silva e Raquel Teixeira"
affiliation: 
    - Escola Nacional de Saúde Pública
date: today
date-format: long
lang: pt 
format:
  html:
    preview: false
    smooth-scroll: true
    embed-resources: true
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 3
    code_download: true
    code-copy: true
execute:
  warning: false
  collapse: true
  message: false
  eval: true
  echo: true
title-block-style: default
theme: templata_ensp
editor: 
  markdown: 
    wrap: 72
project:
  output-dir: outputs/documents
---

```{r}
rm(list = ls(all.names = TRUE)) # limpa todos os objetos, incluindo os ocultos

required_packages <- c("janitor",
                       "tidyverse",
                       "rio",
                       "here",
                       "haven",
                       "data.table",
                       "lubridate",
                       "readxl"
                       )      

for (pkg in required_packages) {
  # install packages if not already present
  if (!pkg %in% rownames(installed.packages())) {
    install.packages(pkg)
  }
  
  # load packages to this current session 
  library(pkg, character.only = TRUE)
}
remove(required_packages)
remove(pkg)
```

# Carregar a base de dados

```{r}

inquerito_AVC_2024 <- read_excel("datasets/inquerito_AVC_2024_processed.xlsx") %>% 
  clean_names()

names(inquerito_AVC_2024)

```
```{r}
nrow(inquerito_AVC_2024)

```

```{r}

summary_inquerito_by_ucc <- inquerito_AVC_2024 %>% 
  summarise(
    count = n(),
.by = ucc
  )

summary_inquerito_by_ucc

```
```{r}
summary_inquerito_by_agrupamento <- inquerito_AVC_2024 %>% 
  summarise(
    count = n(),
.by = agrupamento_escolas
  )

summary_inquerito_by_agrupamento
```


```{r}
grafico_alunos_por_agrupamento <- ggplot(data = summary_inquerito_by_agrupamento, aes(x = agrupamento_escolas,
                                                    y = count))+
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Número de alunos por agrupamento",
       x = "Agrupamento",
       y = "Alunos") +
  theme_minimal()
  
grafico_alunos_por_agrupamento  

```


```{r}
grafico_alunos_por_ucc <- ggplot(data = summary_inquerito_by_ucc, aes(x = ucc,
                                                    y = count))+
  geom_bar(stat = "identity", fill = "#de3e3e") +
  labs(title = "Número de alunos por UCC",
       x = "UCC",
       y = "Alunos") +
  theme_minimal()
  
grafico_alunos_por_ucc 

```
